name: 'dbt_proj'
version: '1.0.0'
config-version: 2

profile: 'dbt_proj'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_proj:
    staging:
      schema: staging
      database: horizons-learning
      +materialized: view